//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcgSoftware.IcalNetHumanReadableExtension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IcgSoftware.IcalNetHumanReadableExtension.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for {0} times.
        /// </summary>
        internal static string CountEnding {
            get {
                return ResourceManager.GetString("CountEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every day.
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {0} days.
        /// </summary>
        internal static string DailyEveryNDays {
            get {
                return ResourceManager.GetString("DailyEveryNDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string DayChainSeparator {
            get {
                return ResourceManager.GetString("DayChainSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourth.
        /// </summary>
        internal static string Fourth {
            get {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th last {0}.
        /// </summary>
        internal static string FourthLastNumeral {
            get {
                return ResourceManager.GetString("FourthLastNumeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last {0}.
        /// </summary>
        internal static string LastNumeral {
            get {
                return ResourceManager.GetString("LastNumeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every month.
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {0} months.
        /// </summary>
        internal static string MonthlyEveryNMonths {
            get {
                return ResourceManager.GetString("MonthlyEveryNMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on the {0}.
        /// </summary>
        internal static string MonthlyOnDay {
            get {
                return ResourceManager.GetString("MonthlyOnDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on the {0}.
        /// </summary>
        internal static string MonthlyOnDayPlural {
            get {
                return ResourceManager.GetString("MonthlyOnDayPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on {0}.
        /// </summary>
        internal static string MonthlyOnNumberedDay {
            get {
                return ResourceManager.GetString("MonthlyOnNumberedDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on the {0}.
        /// </summary>
        internal static string MonthlyOnWeekDay {
            get {
                return ResourceManager.GetString("MonthlyOnWeekDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on the {0}.
        /// </summary>
        internal static string MonthlyOnWeekDayNumeral {
            get {
                return ResourceManager.GetString("MonthlyOnWeekDayNumeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string PhraseFirstCharToUpper {
            get {
                return ResourceManager.GetString("PhraseFirstCharToUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string PhraseStructure {
            get {
                return ResourceManager.GetString("PhraseStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd last {0}.
        /// </summary>
        internal static string SecondLastNumeral {
            get {
                return ResourceManager.GetString("SecondLastNumeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to third.
        /// </summary>
        internal static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd last {0}.
        /// </summary>
        internal static string ThirdLastNumeral {
            get {
                return ResourceManager.GetString("ThirdLastNumeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until {0}.
        /// </summary>
        internal static string UntilDateEnding {
            get {
                return ResourceManager.GetString("UntilDateEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMMM dd, yyyy.
        /// </summary>
        internal static string UntilDateEndingDateFormat {
            get {
                return ResourceManager.GetString("UntilDateEndingDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every week.
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on {0}.
        /// </summary>
        internal static string WeeklyDays {
            get {
                return ResourceManager.GetString("WeeklyDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every day.
        /// </summary>
        internal static string WeeklyEveryDay {
            get {
                return ResourceManager.GetString("WeeklyEveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {0} weeks.
        /// </summary>
        internal static string WeeklyEveryNWeeks {
            get {
                return ResourceManager.GetString("WeeklyEveryNWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every weekday.
        /// </summary>
        internal static string WeeklyEveryWeekday {
            get {
                return ResourceManager.GetString("WeeklyEveryWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every year.
        /// </summary>
        internal static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {0} years.
        /// </summary>
        internal static string YearlyEveryNYears {
            get {
                return ResourceManager.GetString("YearlyEveryNYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on {0} the {1}.
        /// </summary>
        internal static string YearlyOnDay {
            get {
                return ResourceManager.GetString("YearlyOnDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMMM.
        /// </summary>
        internal static string YearlyOnDayMonthPattern {
            get {
                return ResourceManager.GetString("YearlyOnDayMonthPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on {0} {1} of {2}.
        /// </summary>
        internal static string YearlyOnNumbered {
            get {
                return ResourceManager.GetString("YearlyOnNumbered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMMM.
        /// </summary>
        internal static string YearlyOnNumberedMonthFormat {
            get {
                return ResourceManager.GetString("YearlyOnNumberedMonthFormat", resourceCulture);
            }
        }
    }
}
