//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcgSoftware.RecurrenceRuleToText {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IcgSoftware.RecurrenceRuleToText.Language.fr", typeof(Language_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to à {0} reprises.
        /// </summary>
        internal static string CountEnding {
            get {
                return ResourceManager.GetString("CountEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tous les jours.
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tous les {0} jours.
        /// </summary>
        internal static string DailyEveryNDays {
            get {
                return ResourceManager.GetString("DailyEveryNDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jour.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to et.
        /// </summary>
        internal static string DayChainLastSeparator {
            get {
                return ResourceManager.GetString("DayChainLastSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to premier.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quatrième.
        /// </summary>
        internal static string Fourth {
            get {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le quatrième {0} dernier.
        /// </summary>
        internal static string FourthLastNumeral {
            get {
                return ResourceManager.GetString("FourthLastNumeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dernier.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le dernier {0}.
        /// </summary>
        internal static string LastNumeral {
            get {
                return ResourceManager.GetString("LastNumeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to et.
        /// </summary>
        internal static string MonthChainLastSeparator {
            get {
                return ResourceManager.GetString("MonthChainLastSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tous les mois.
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tous les {0} mois.
        /// </summary>
        internal static string MonthlyEveryNMonths {
            get {
                return ResourceManager.GetString("MonthlyEveryNMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le {0}.
        /// </summary>
        internal static string MonthlyOnDay {
            get {
                return ResourceManager.GetString("MonthlyOnDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to les {0}.
        /// </summary>
        internal static string MonthlyOnDayPlural {
            get {
                return ResourceManager.GetString("MonthlyOnDayPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le {0}.
        /// </summary>
        internal static string MonthlyOnNumberedDay {
            get {
                return ResourceManager.GetString("MonthlyOnNumberedDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le {0}.
        /// </summary>
        internal static string MonthlyOnWeekDay {
            get {
                return ResourceManager.GetString("MonthlyOnWeekDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string MonthlyOnWeekDayNumeral {
            get {
                return ResourceManager.GetString("MonthlyOnWeekDayNumeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string PhraseFirstCharToUpper {
            get {
                return ResourceManager.GetString("PhraseFirstCharToUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string PhraseStructure {
            get {
                return ResourceManager.GetString("PhraseStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deuxième.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l&apos;avant-dernier {0}.
        /// </summary>
        internal static string SecondLastNumeral {
            get {
                return ResourceManager.GetString("SecondLastNumeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to troisième.
        /// </summary>
        internal static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le troisième {0} dernier.
        /// </summary>
        internal static string ThirdLastNumeral {
            get {
                return ResourceManager.GetString("ThirdLastNumeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jusqu&apos;au {0}.
        /// </summary>
        internal static string UntilDateEnding {
            get {
                return ResourceManager.GetString("UntilDateEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd MMMM yyyy.
        /// </summary>
        internal static string UntilDateEndingDateFormat {
            get {
                return ResourceManager.GetString("UntilDateEndingDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jour ouvrable.
        /// </summary>
        internal static string Weekday {
            get {
                return ResourceManager.GetString("Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jour du weekend.
        /// </summary>
        internal static string WeekendDay {
            get {
                return ResourceManager.GetString("WeekendDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toutes les semaines.
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le {0}.
        /// </summary>
        internal static string WeeklyDays {
            get {
                return ResourceManager.GetString("WeeklyDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tous les jours.
        /// </summary>
        internal static string WeeklyEveryDay {
            get {
                return ResourceManager.GetString("WeeklyEveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toutes les {0} semaines.
        /// </summary>
        internal static string WeeklyEveryNWeeks {
            get {
                return ResourceManager.GetString("WeeklyEveryNWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tous les jours.
        /// </summary>
        internal static string WeeklyEveryWeekday {
            get {
                return ResourceManager.GetString("WeeklyEveryWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tous les ans.
        /// </summary>
        internal static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tous les {0} ans.
        /// </summary>
        internal static string YearlyEveryNYears {
            get {
                return ResourceManager.GetString("YearlyEveryNYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le {1} {0}.
        /// </summary>
        internal static string YearlyOnDay {
            get {
                return ResourceManager.GetString("YearlyOnDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMMM.
        /// </summary>
        internal static string YearlyOnDayMonthPattern {
            get {
                return ResourceManager.GetString("YearlyOnDayMonthPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en {0}.
        /// </summary>
        internal static string YearlyOnMonth {
            get {
                return ResourceManager.GetString("YearlyOnMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le {0} {1} de {2}.
        /// </summary>
        internal static string YearlyOnNumbered {
            get {
                return ResourceManager.GetString("YearlyOnNumbered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMMM.
        /// </summary>
        internal static string YearlyOnNumberedMonthFormat {
            get {
                return ResourceManager.GetString("YearlyOnNumberedMonthFormat", resourceCulture);
            }
        }
    }
}
